### ISSUE TITLE
Change the default player on Devices to native player

### ISSUE THREAD

**Issue by aniketdharia** [adaptlearning/adapt-contrib-media#104]
Change the default player on Devices to native player to resolve the accidental tap while scrolling.

**Comment by moloko** [comment]
the accidental tap issue should be fixed in v2



—
Matt Leathes

**Comment by aniketdharia** [comment]
Ok . I checked the code. Will take it up for testing and if it works will close this issue.

Thanks

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#858
