### ISSUE TITLE
What version of flash is needed for fallback?

### ISSUE THREAD

**Issue by zenduo** [adaptlearning/adapt-contrib-media#111]

**Comment by oliverfoster** [comment]
Whatever the last supported windows xp ie8 version was (and up I presume?). I use it on my test kit.

**Comment by moloko** [comment]
hhmm good question. According to [this](https://github.com/johndyer/mediaelement/blob/master/build/mediaelement.js#L31) it's detecting 9.0.124 but if I inspect the actual mediaelement.swf using SWFDecompiler it's says it's been published for Flash Player 10.0

**Comment by moloko** [comment]
We've generally told clients that Flash Player 10 is required for IE8 video support

**Comment by zenduo** [comment]
OK, I'll let @chucklorenz know for the wiki.
