### ISSUE TITLE
[develop] adapt-contrib-media - if features are defined then _useClosedCaptions is not used

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt-contrib-media#128]
The lines https://github.com/adaptlearning/adapt-contrib-media/blob/develop/js/adapt-contrib-media.js#L34-L39 wraps the `_useClosedCaptions` test which then is only tested when features are undefined, this should be separated, also defining all features second time is redundant when you can only add "tracks" to the feature list.

```
    if (modelOptions.features === undefined) {
        modelOptions.features = ['playpause', 'progress', 'current', 'duration'];
    }
    //at this point features will not be undefined
    var ccFeature = "tracks";
    if (this.model.get("_useClosedCaptions") && modelOptions.features.indexOf(ccFeature) == -1) {
        modelOptions.features.push(ccFeature);
    }

```

**Comment by taylortom** [comment]
You're right this could be simplified a bit.

```
if (features undefined)
      if(cc) features = ['playpause', 'progress', 'tracks', 'current', 'duration']
      else features = ['playpause', 'progress', 'current', 'duration']
```

I don't really have a problem with the outer `modelOptions.features === undefined` wrapper, as everything inside is features-related.

I'm not sure your proposed solution would be suitable, as I think the indices of the items are used when rendering (i.e. tracks button is needed before the timers in this case) - should probably do a splice here.

**Comment by taylortom** [comment]
Also (thinking about this a bit more), do we want to force-add the CC button if the features list has been specified via JSON?

**Comment by LukaszGrela** [comment]
The use of `_useClosedCaptions` property will force it so if user will not define the features but use this prop should have the tracks added.
