### ISSUE TITLE
Audio not showing volumen control

### ISSUE THREAD

**Issue by jscampos** [adaptlearning/adapt-contrib-media#133]
I have a page with a video and audio, the video does display the volumen controller while the audio doesn't, any idea how to add it to the audio?

**Comment by moloko** [comment]
The media player won't show the volume control unless you tell it to. If you want add volume control to the end of the normal player bar, add this to your json for the media component:
```
"_playerOptions": {
    "features": ["playpause","progress","current","duration","volume"]
}
```

**Comment by jscampos** [comment]
Thanks!
