### ISSUE TITLE
Not working on youtube video on iPad 

### ISSUE THREAD

**Issue by mike-st** [adaptlearning/adapt-contrib-media#134]
This component doesn't seem to work with youtube video's on the iPad. I have tried using an embed link and a watch link and neither will work on iOS it crashes. May have some issue with https on the iPad from the look of the errors. I have 24 video's on the module I am testing on and it throws back this error in the browser and crashes. Below I have included a picture of the errors and the code for my component. 

![adapt-ipad-youtube-issue](https://cloud.githubusercontent.com/assets/10455453/11733227/56b251be-9f79-11e5-8680-de96104d14e5.jpg)

    "_id":"c-05",
    "_parentId":"b-05",
    "_type": "component",
    "_layout": "full",
    "body": "",
    "displayTitle": "Introduction",
    "title": "Introduction",
    "_pageLevelProgress": {
      "_isEnabled": true
    },
    "_classes": "",
    "_component": "media",
    "_playerOptions": "",
    "_transcript": {
      "transcriptLink": "",
      "transcriptLinkButton": "",
      "inlineTranscriptBody": "",
      "inlineTranscriptCloseButton": "",
      "inlineTranscriptButton": "",
      "_externalTranscript": false,
      "_inlineTranscript": false
    },
    "_useClosedCaptions": false,
    "_setCompletionOn": "ended",
    "_media": {
      "cc": [],
      "poster": "",
      "type": "video/youtube",
      "source": "//www.youtube.com/embed/uhH4KGxcOjs",
      "mp3": "",
      "ogv": "",
      "mp4": ""
    },
    "instruction": ""
  }

**Comment by moloko** [comment]
hi @mike-st 
the 'embed' style links definitely shouldn't be used, only the 'watch' links
The console errors are all cross-domain security warnings for some reason - do the above errors still occur if you change to 'watch' style youtube URLs?

**Comment by mike-st** [comment]
Hi Moloko
Did some testing over the weekend and I am now just using the https://youtu.be/ url that youtube gives as sharing option instead of the embed. I am still getting the error but only on the iPAD not on the Desktop browsers. I am pretty sure something weird is going on with the media component and the iOS. As it works as it should with the desktop browsers. I took a couple of screenshots where I tested the youtube video's on my local MAMP server and my external vubiz.com url. It does something strange on the iPAD it puts a "http://www.youtube.com/embed/" in front of the proper video url "https://youtu.be/uhH4KGxc0js". This seems to be the issue why it is erroring out just on the IOS system as it doesn't do this on the desktop browsers. Here are some screenshots of the errors on the iPAD and warnings too.
![ipad-issue-server-error2](https://cloud.githubusercontent.com/assets/10455453/11781729/d37a3000-a239-11e5-8cfd-f91274f1731a.jpg)
![ipad-issue-server-error](https://cloud.githubusercontent.com/assets/10455453/11781731/d397c534-a239-11e5-9e64-73a23a327d93.jpg)
![ipad-issue-error](https://cloud.githubusercontent.com/assets/10455453/11781730/d391c5da-a239-11e5-80bf-586756de199a.jpg)

**Comment by moloko** [comment]
The correct URL to use is the one with 'watch' in the URL, for example:
//www.youtube.com/watch?v=uhH4KGxcOjs
This is the same URL that is shown in the browser's address bar when you view a video on the YouTube website, minus any querystring parameters (it may be that you can safely include those, I haven't tried)

**Comment by moloko** [comment]
I'm pretty sure the YouTube video itself will have to have the setting 'Allow embedding' (advanced settings > distribution options) checked... obviously this is only something you can control for your own videos.

**Comment by mike-st** [comment]
Hi yes I know all about the Allow embedding in the youtube video's and my test were done with it checked off. That is not this issue here.

**Comment by moloko** [comment]
and what if you try the other form of URL? i.e. //www.youtube.com/watch?v=uhH4KGxcOjs

**Comment by moloko** [comment]
@mike-st just downloaded the framework and tried with the URL //www.youtube.com/watch?v=uhH4KGxcOjs - works fine for my on my iPad Mini and iPhone 4S (iOS 9.1). 

It did take a rather long time to actually load the player on the iPhone 4S but that could be just as much to do with the age of the hardware on that device.

**Comment by mike-st** [comment]
Good point I will try that out, when I have my iPad on me next. Still is a bit weird though even with out adding that in yet why the desktop browser would act differently than the safari iOS. On the desktop it doesn't add in the extra "http://www.youtube.com/embed/" in front of the youtube video path. I will try what you mentioned though and let you know.

**Comment by mike-st** [comment]
Yeah it is really slow, not sure why, specially in comparison to the older youtube component I use to use...
https://github.com/cgkineo/adapt-youtube
I would use it but it doesn't work with the authoring tool very well as it is Version 1 compatible

**Comment by moloko** [comment]
@mike-st that's a fair point. The underlying media player is actually [mediaelementjs](http://mediaelementjs.com/) so all this is actually being handled by that player; this component really just turns it into an Adapt plugin.

I'll try and find some time this week to update adapt-youtube for the authoring tool.

**Comment by mike-st** [comment]
Oh I see I noticed mediaelementjs when I was inspecting the video. Seems like a robust player, kind of like jwplayer, possibly better though I think? That would be great if your able to update the adapt-youtube component it worked amazingly in Version 1.  Thanks for your help again and I will let you know when I test the watch youtube link next on the iPad

**Comment by moloko** [comment]
Yeah it's OK, it has been quite challenging to get it to this point though! JWPlayer is probably better but unfortunately is a paid-for solution so not really something we can include. I think it also doesn't support IE8?

**Comment by moloko** [comment]
hi @mike-st - how did you get on with this?

By the way, I have now added a properties.schema to [adapt-youtube](https://github.com/cgkineo/adapt-youtube) as well as implementing [several other improvements](https://github.com/cgkineo/adapt-youtube/commit/a7f7897a9d55899ad81170fb6cacfc60954d55f6). When you get a sec could you give it a try in the AT and let me know how you get on?

**Comment by mike-st** [comment]
WOW thanks so much Moloko! I meant to get back seems the Watch rather than embed link does work the best on the iPad still brings up errors and is slow, but doesn't crash so that is good. I would be happy to try out the adapt-youtube component. Thanks again for all your help

**Comment by moloko** [comment]
No problem at all, Mike. I'm off now until 2016 so no rush to get back to me.

**Comment by mike-st** [comment]
Have a good holiday
