### ISSUE TITLE
Closed Captions default to OFF if srclang is not english

### ISSUE THREAD

**Issue by robertmausser** [adaptlearning/adapt-contrib-media#235]
setting  "srclang": "fr" when there is no alternative or other caption defaults to OFF. This is for a french only course where there is only french, never english. 

This shouldn't be. The deciding factor for default to on should be toggled and decided by another property, the assumption should not be that a course is provided in english first and another language as supplementary.

**Comment by chris-steele** [comment]
@robertmausser I suspect you may be missing `"_startLanguage": "fr"` from your media component JSON, could you see if this resolves the issue?

@oliverfoster it might be worth adding this property to the [default JSON](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/components.json#L203), what do you think?

**Comment by oliverfoster** [comment]
yea, sure, go for it, it's in the readme already https://github.com/adaptlearning/adapt-contrib-media#_startlanguage-string
