### ISSUE TITLE
Add support for localisation of the player interface

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-contrib-media#238]
Currently there's no way to change any of the mediaelement.js UI labels from the default (English)

This could be done either through implementing i18n as per [this demo](https://github.com/johndyer/mediaelement/blob/master/demo/mediaelementplayer-translation.html) or by simply amending the labels directly via `mejs.MepDefaults` e.g. `mejs.MepDefaults.fullscreenText = "Plein écran";`

I think the latter might be better with Adapt

Caption language label text also needs adding: https://github.com/johndyer/mediaelement/blob/master/installation.md#use-of-closed-captioning-optional

**Comment by oliverfoster** [comment]
just needs these:
https://github.com/adaptlearning/adapt-contrib-media/blob/03f163b7ce56fb747dac15cc68efa76cac636d0a/properties.schema#L23-L166

adding to the new schema

**Comment by chris-steele** [comment]
Resolved by https://github.com/adaptlearning/adapt-contrib-media/pull/230.
