### ISSUE TITLE
Convert controls offset custom class to json property

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt-contrib-media#242]
### Subject of the enhancement
To enable the offset media controls feature a user is required to manually type out the custom class `offset-media-controls` into the components _classes field within the frameworks json file or into the corresponding _classes field within the authoring tool.

### Your environment
* v5.x FW / AAT

### Expected behaviour
Create a boolean / checkbox property that applies the custom class

**Comment by guywillis** [comment]
potential hiccup to this request.

the styling associated with this custom class is located in the theme. moving the custom class to the plugin would counteract the efforts of having only structural less in the plugin

**Comment by oliverfoster** [comment]
any progress?

**Comment by kirsty-hames** [comment]
> the styling associated with this custom class is located in the theme. moving the custom class to the plugin would counteract the efforts of having only structural less in the plugin

Hey @guywillis, I don't see an issue with moving the theme styling for this over to the plugin. Media is a niche plugin where it utilises a third party player and we already have non-structual CSS (`background` properties and `padding` etc) in the plugin [`mep.less`](https://github.com/adaptlearning/adapt-contrib-media/blob/master/less/mep.less) and [`mep-overrides.less`](https://github.com/adaptlearning/adapt-contrib-media/blob/master/less/mep-overrides.less). 

Maybe add this to [`media.less`](https://github.com/adaptlearning/adapt-contrib-media/blob/d88561ca0e32c6b3f5edacc95011f663fc5046dc/less/media.less#L47) where we already have media specific overrides/fixes?
