### ISSUE TITLE
Convert invert play icon custom class to json property

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt-contrib-media#243]
### Subject of the enhancement
To enable the inverted play icon feature a user is required to manually type out the custom class `invert-play-icon` into the components _classes field within the frameworks json file or into the corresponding _classes field within the authoring tool.

### Your environment
* v5.x FW / AAT

### Expected behaviour
Create a boolean / checkbox property that applies the custom class

**Comment by guywillis** [comment]
potential hiccup to this request.

the styling associated with this custom class is located in the theme. moving the custom class to the plugin would counteract the efforts of having only structural less in the plugin

**Comment by oliverfoster** [comment]
closing as stale
