### ISSUE TITLE
Android fullscreen portrait aspect ratio

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-media#248]
As a result of https://github.com/adaptlearning/adapt-contrib-media/pull/217, when a video is run fullscreen on an Android device, in portrait orientation, the aspect ratio of the video is incorrect as it is stretched to fill the viewport. This doesn't occur if using native Android controls via `_playerOptions.AndroidUseNativeControls: true`. The issue is restricted to Android only as iOS switches to native controls automatically when run fullscreen.

**Comment by kirsty-hames** [comment]
Waiting on testing to confirm [fix](https://github.com/adaptlearning/adapt-contrib-media/commit/09f0043ce4ea4bf7464cc775075541569416aa9a) before opening a PR...
