### ISSUE TITLE
Add option to control playback rate of Videos

### ISSUE THREAD

**Issue by zupzup** [adaptlearning/adapt-contrib-media#260]
### Subject of the issue/enhancement/features

People are used to be able to control the playback speed of videos and having this option would further increase the UX of e-learning courses created using Adapt.
Using the latest version of `Mediaelement` should make this possible, but I'm not sure how much effort it would be to upgrade it in this project.

### Your environment

All

### Steps to reproduce

Include any video, watch in any browser - there's no way to control the playback rate

### Expected behaviour

There should be a control option in the video menu, where people can speed up video playback, or slow it down

### Actual behaviour

There is no way to manipulate video playback speed currently

**Comment by swashbuck** [comment]
Hi, @zupzup . Have you tried the 'speed' option in `_playerOptions.features`? It's not document in the Media plugin itself, but it can be used.

```
    "_playerOptions": {
      "alwaysShowControls": true,
      "features": [
        "playpause",
        "progress",
        "tracks",
        "current",
        "duration",
        "fullscreen",
        "volume",
        "speed"
      ]
    },
```

**Comment by zupzup** [comment]
@swashbuck that's exactly what I was looking for, awesome! Thank you :)
