### ISSUE TITLE
v1.1.0: Video component, play button issue, in ie8 (XP)

### ISSUE THREAD

**Issue by kineoluke** [adaptlearning/adapt-contrib-media#39]
When clicking quickly on, or between, the two play buttons (smaller one in the bottom left, bigger one on the actual video), I can produce either of two bugs:

(1) The bigger play button appears and then won't disappear even as the video continues to play behind it; when this happens the smaller (bottom-left) button doesn't change visual state to a pause icon (although it does pause the video): 

![capture-2](https://cloud.githubusercontent.com/assets/7656268/3040414/9b4427e2-e0eb-11e3-85ce-a22bde10a39a.JPG)

(2) The loading/buffering icon appears and animates perpetually:

![capture](https://cloud.githubusercontent.com/assets/7656268/3040323/b242dbf6-e0ea-11e3-9c95-fbf52b83b2f6.JPG)

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#855
