### ISSUE TITLE
v1.1.0 b6: null errors when navigating back during video play (IE8) 

### ISSUE THREAD

**Issue by shauncg** [adaptlearning/adapt-contrib-media#46]
Navigating back to the previous menu/level whilst a video is still playing generates the following errors: 

> Webpage error details
> 
> User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; GTB7.5; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; InfoPath.2; .NET4.0C; .NET4.0E)
Timestamp: Fri, 23 May 2014 15:07:36 UTC
> 
> Message: 'null' is null or not an object
> Line: 1
> Char: 519
> Code: 0
> URI: https://community.adaptlearning.org/pluginfile.php/1353/mod_scorm/content/3/index.html

(Above from "Message" repeats an additional 6 times.)

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-media/issues/46 < fixed here
