### ISSUE TITLE
Too easy to start video playing on touch-capable devices

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-contrib-media#71]
Currently any touch on the poster image of the video player will start it playing - making it really likely that you will accidentally start the video playing when just trying to scroll.

If you switch to using native media controls then this issue does not occur - but currently you can't do this from the JSON. It also slightly negates the whole point of using MediaElement which is to have a consistent look and feel across platforms.

You can also fix this issue via a CSS hack.

Suggest implementing both the CSS hack and also making the extra settings for MediaElement available via JSON (#72)

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-347
