### ISSUE TITLE
make the additional settings of MediaElement available via JSON

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-contrib-media#72]
probably best to have a generic 'options' object so that if we change to a different underlying player, or stick with MediaElement and it changes an option name or adds an option, we don't have to update our code.

**Comment by LukaszGrela** [comment]
The easiest would be to expose features list, component code would validate entries and translate into correct versions if changed (old version props).

    "_features":[],

then in code


    validateFeatures: function(features) {
        if(features)
        {
            var valid = [];
            //process validation
            //...
            return valid;
        }
        else
        {
            //use default
            return ['playpause','progress','current','duration'];
        }
    }
    //...
    postRender: function(){
        //...
        features: this.validateFeatures(this.model.get("_features"))
        //...
    }

**Comment by oliverfoster** [comment]
+1
