### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-media#78]
https://github.com/adaptlearning/adapt-contrib-media/blob/master/js/adapt-contrib-media.js#L54

If component is loaded but never comes into view this event will never get detached and will persist in ie8>9 (possibly 10).

Need to use backbone events: {} object instead so that event delegation and undelegation is handles by the view.

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-475
