### ISSUE TITLE
Audioplayer not responsive

### ISSUE THREAD

**Issue by MartinSandberg** [adaptlearning/adapt-contrib-media#81]
Hi,

Trying to use audio with the media element in my Adapt course. It's working but the player is not responsive. It gets a fixed size and stays like that on all widths of the screen.

Having the player in a component with _layout "right". The width of the audioplayer does not change even if I set it in _layout "full".

This leads to the problem that as the component gets a smaller width the player starts to stick out on the side of the component.

Updated to the latest code from here and it is still not working. How can I get it to become responsive?

BR,
Martin

**Comment by LukaszGrela** [comment]
In the `postRender` of `adapt-contrib-media.js` you can put following to teh config object:

                audioWidth: '100%',

It resolves this issue (however I've noticed that in layout right component the time part is wrapped and goes out of the box).

**Comment by LukaszGrela** [comment]
The media component is using MEP 2.13.2, you can pull this branch and edit the `mep-player.js` in the `setControlsSize` function

    // fit the rail into the remaining space
    railWidth = Math.floor(t.controls.width() - usedWidth - (rail.outerWidth(true) - rail.width())) - 1;

I have added `Math.floor` and substracted 1 px from this, this will resolve this issue

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-486
