### ISSUE TITLE
Develop branch properties.schema needs updating

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-media#97]
Needed for framework v2.0 and authoring tool compatibility.

Needs latest schema format applying with new elements such as _useClosedCaptions, _playerOptions.

And _transcript

**Comment by markl55** [comment]
Hi Dan,

When whoever is working on this would they also add the properties that enable a vimeo/utube URL to get added? Currently they are not exposed in the properties page in the authoring Tool.

They seem to be in the handlebars template

https://github.com/adaptlearning/adapt-contrib-media/blob/master/templates/media.hbs#L12

**Comment by moloko** [comment]
these were added back in July
