### ISSUE TITLE
Duplicate setupEventListeners Functions in develop branch

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-media#98]
Appear to have identical duplicate setupEventListeners functions

https://github.com/dancgray/adapt-contrib-media/blob/develop/js/adapt-contrib-media.js#L50

https://github.com/dancgray/adapt-contrib-media/blob/develop/js/adapt-contrib-media.js#L94

**Comment by moloko** [comment]
Good catch! Looks as if something went a bit wrong in this merge: https://github.com/adaptlearning/adapt-contrib-media/commit/114a66268bd64b4c23abcd5d45a722c143cf53de

**Comment by dancgray** [comment]
This is not resolved.
